#!/bin/bash
/usr/share/openvswitch/scripts/ovs-ctl start
ovs-vsctl add-br br0
ovs-vsctl add-port br0 net1
ovs-vsctl add-port br0 vxlan1 -- set interface vxlan1 type=vxlan options:remote_ip=192.168.16.2
