apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    peers:
    - my-asn: 64512
      peer-asn: 64512
      peer-address: 10.10.10.1
    address-pools:
    - name: my-ip-space
      protocol: bgp
      addresses:
      - 10.10.100.0/24