apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  namespace: default
spec:
  rules:
  - http:
      paths:
      - path: /service-one
        backend:
          serviceName: my-nginx
          servicePort: 80
      - path: /service-two
        backend:
          serviceName: my-nginx-2
          servicePort: 80