apiVersion: v1
kind: Pod
metadata: 
  name: pod1-worker1
spec:
  containers:
  - name: busy1-1
    image: busybox
    command:
      - sleep
      - "3600"
  - name: busy1-2
    image: busybox
    command:
      - sleep
      - "3600"
  nodeSelector:
    kubernetes.io/hostname: k8s-worker1
