---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-configmap-2
data:
  index.html: |
    <h1>This is nginx-two!!!</h1>

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: my-nginx-deployment-2
spec:
  selector:
    matchLabels:
      app: my-nginx-2
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: my-nginx-2
    spec:
      containers:
        - name: my-nginx-2
          image: nginx:1.14.2
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-webpage-2
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-webpage-2
          configMap:
            name: nginx-configmap-2