---


  - name: Include kubespray tasks
    include: kubespray/cluster.yml
    tags: kubespray

  - hosts: kube-master[0]
    roles:
      - metallb
    tags: metallb

  - hosts: kube-master[0]
    roles:
      - nginx-ingress
    tags: nginx-ingress
